system-core:
  - linux-cachyos
  - linux-cachyos-headers
  - systemd
  - systemd-sysvcompat
  - dbus
  - dbus-broker-units
  - dbus-glib
  - glib2
  - polkit
  - shadow
  - lua-luv
  - gpgme
  - gnupg
  - ufw
system-toolchains:
  - llvm-libs
  - clang
dev-languages:
  - go
  - python-numpy
  - python-matplotlib
gui-frameworks:
  - qt5-base
  - qt6-base
  - qt6-declarative
  - electron39
update-notifier:
  - python-pystray
  - python-pillow
  - librsvg
fonts-heavy:
  - noto-fonts-cjk
  - ttf-meslo-nerd
gaming-runtimes:
  - proton-cachyos
  - proton-cachyos-slr
  - wine
  - wine-cachyos-opt
bootc:
  - bootc
  - dracut
  - ostree
  - skopeo
  - btrfs-progs
  - e2fsprogs
  - xfsprogs
  - dosfstools
fonts:
  - ttf-ms-fonts
  - ttf-dejavu
  - ttf-bitstream-vera
  - ttf-ubuntu-font-family
  - noto-fonts
  - noto-fonts-emoji
  - noto-color-emoji-fontconfig
  - ttf-nerd-fonts-symbols
  - ttf-nerd-fonts-symbols-mono
  - awesome-terminal-fonts
  - cantarell-fonts
  - ttf-opensans
filesystems:
  - fuse2
  - fuse3
  - fuse2fs
  - ntfs-3g
  - exfatprogs
  - lvm2
  - mdadm
  - cryptsetup
  - gvfs
  - gvfs-mtp
  - gvfs-smb
  - nfs-utils
  - smartmontools
  - nilfs-utils
  - dmraid
  - autofs
archiving:
  - unp
  - unarj
  - unrar
  - unzip
  - zip
  - bzip2
  - p7zip
  - unace
  - cpio
  - sharutils
  - cabextract
  - rpmextract
  - xz
printing-scanning:
  - cups
  - cups-pdf
  - system-config-printer
  - sane
  - cups-filters
  - foomatic-db
  - foomatic-db-engine
  - foomatic-db-gutenprint-ppds
  - foomatic-db-nonfree
  - foomatic-db-nonfree-ppds
  - foomatic-db-ppds
  - ghostscript
  - gsfonts
  - gutenprint
  - splix
  - hplip
  - python-pyqt5
  - python-reportlab
  - cups-browsed
  - ipp-usb
  - sane-airscan
audio:
  - pipewire-pulse
  - pipewire-alsa
  - pipewire-jack
  - wireplumber
  - pavucontrol
  - alsa-utils
firmware:
  - amd-ucode
  - intel-ucode
  - linux-firmware
  - sof-firmware
  - alsa-firmware
  - wireless-regdb
  - linux-firmware-marvell
networking:
  - networkmanager
  - networkmanager-openvpn
  - wpa_supplicant
  - iwd
  - ethtool
  - dnsutils
  - modemmanager
  - usb_modeswitch
  - nss-mdns
  - bluez
  - bluez-utils
  - bluez-libs
  - bluez-obex
  - bluedevil
  - openvpn
  - wireguard-tools
  - pptpclient
  - cloudflare-warp-bin
  - tailscale
  - dnsmasq
  - xl2tpd
  - bluez-hid2hci
  - mullvad-vpn-bin
  - mullvad-vpn-daemon-bin
hardware-management:
  - power-profiles-daemon
  - cpupower
  - upower
  - accountsservice
  - rtkit
  - xdg-user-dirs
  - mousetweaks
  - radeontool
  - fwupd
  - dmemcg-booster
  - hwinfo
  - dmidecode
  - hdparm
  - lsscsi
  - sg3_utils
  - mtools
  - chwd
  - hwdetect
shells:
  - bash
  - zsh
  - fish
  - bash-preexec
  - bash-completion
  - zsh-completions
  - oh-my-zsh-git
  - atuin
  - starship
cli-utilities:
  - zoxide
  - eza
  - ripgrep
  - tealdeer
  - fd
  - fzf
  - jq
  - btop
  - iotop-c
  - konsave
  - conky
  - sysstat
  - htop
  - fastfetch
  - glances
  - procs
  - bottom
  - rsync
  - rclone
  - wl-clipboard
  - procps-ng
  - curl
  - wget
  - man-db
  - man-pages
  - openssh
  - openssl
  - pacman-contrib
  - pkgfile
  - plocate
  - duf
  - fsarchiver
  - pv
  - chafa
text-editors-ides:
  - nano
  - nano-syntax-highlighting
  - micro
  - vi
  - visual-studio-code-bin
  - meld
  - vim
devel-base:
  - git
  - git-lfs
  - tig
  - github-cli
  - paru
  - just
  - cosign
  - skopeo
containers:
  - docker
  - docker-compose
  - podman
  - podman-compose
  - distrobox
  - flatpak
  - ptyxis
schedulers:
  - scx-scheds-git
  - scx-tools-git
  - scx-manager
desktop-integration:
  - xorg-xwayland
  - xdg-utils
  - libappimage
  - gtk3
  - gtk4
  - nss
  - libnotify
  - libxss
  - libappindicator-gtk3
  - libsecret
  - libgsf
  - libopenraw
  - poppler-glib
  - espeak-ng
  - orca
themes-aesthetics:
  - cachyos-wallpapers
  - cachyos-plymouth-theme
  - cachyos-plymouth-bootanimation
media-video:
  - libdvdcss
  - gst-libav
  - mpv-git
  - ffmpeg
  - gpu-screen-recorder-ui
  - ffmpegthumbnailer
  - gst-plugin-pipewire
  - gst-plugins-bad
  - gst-plugins-ugly
  - yt-dlp
gaming-core:
  - xorg-xwininfo
  - xdotool
  - scopebuddy-git
  - yad
  - mangohud
  - lutris
  - heroic-games-launcher
  - steam
  - lib32-glibc
  - lib32-gcc-libs
  - lib32-systemd
  - lib32-libx11
  - winboat
  - gamescope-session-git
  - sunshine
  - lact
  - coolercontrol
  - openrgb
  - openrgb-plugin-effects-git
  - nvtop
  - lsfg-vk
  - game-devices-udev
  - udev-joystick-blacklist-git
  - waydroid
  - goverlay
  - pascube
  - vkbasalt
  - vkbasalt-cli
  - vkd3d
  - lib32-vkd3d
  - python-pefile
  - python-pyclip
web-browsers:
  - helium-browser-bin
  - cachyos-firefox-settings
  - firefox
development-languages:
  - nodejs
  - npm
  - rust
  - python-pip
  - python-pipx
  - ruby
  - php
  - cargo-binstall
  - cargo-update
  - python-defusedxml
  - python-packaging
cachyos-settings:
  - cachyos-settings
  - cachyos-micro-settings
  - cachyos-ananicy-rules
  - cachyos-zsh-config
  - cachyos-fish-config
  - cachyos-samba-settings
base-meta:
  - base-devel
  - cachyos-gaming-applications
  - cachyos-gaming-meta
